name = "shiruko-walk-scores"
main = "index.ts"
compatibility_date = "2026-09-08"

[vars]
ALLOWED_ORIGIN = "https://kuronekoug.github.io"

[[d1_databases]]
binding = "DB"
database_name = "shiruko-walk"
database_id = "e7a06315-ab0f-4450-b2ac-054267c20b3d"
